on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install module with optional dependency
      run: |
        echo @jcansdale-test:registry=https://npm.pkg.github.com > .npmrc
        npm login --registry=https://npm.pkg.github.com -u token -p ${{ secrets.GITHUB_TOKEN }}
        npm install @jcansdale-test/npm-fails@1.0.0 --verbose
